apiVersion: v1
kind: ReplicationController
metadata:
  name: gateway
spec:
  replicas: 4
  selector:
    app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: quay.io/bluecat/gateway:20.6.1
        env:
        - name: BAM_IP
          value: "10.24.21.76" # change this
        ports:
        - containerPort: 8000
